// <auto-generated />
using System;
using CreditCardRewards.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditCardRewards.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615202433_InitialSqliteCreate")]
    partial class InitialSqliteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CreditCardRewards.Data.Models.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccumulatedRewardPoints")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccumulatedSpend")
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportLoungeBenefits")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualFeeWaiverSpendThreshold")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaseRewardPointValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseRewardRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseRewardUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelBenefits")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("JoiningFee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherBenefits")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferPartners")
                        .HasColumnType("TEXT");

                    b.Property<string>("TravelBenefits")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WelcomeOffer")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WelcomeOfferValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RewardValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpendThreshold")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.RewardCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveUntil")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxRewardValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.ToTable("RewardCaps");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.RewardCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cap")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveUntil")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RewardMultiplier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId", "Category")
                        .IsUnique();

                    b.ToTable("RewardCategories");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.RewardOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FlatBonusAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxRewardPerTransaction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardBasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RewardMultiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.ToTable("RewardOffers");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashbackEarned")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContributedToFeeWaiver")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContributedToMilestone")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EffectiveReturnPercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Merchant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsEarned")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RewardValueInRupees")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId", "TransactionDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.CreditCard", b =>
                {
                    b.HasOne("CreditCardRewards.Data.Models.UserProfile", "UserProfile")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.Milestone", b =>
                {
                    b.HasOne("CreditCardRewards.Data.Models.CreditCard", "CreditCard")
                        .WithMany("Milestones")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.RewardCap", b =>
                {
                    b.HasOne("CreditCardRewards.Data.Models.CreditCard", "CreditCard")
                        .WithMany("RewardCaps")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.RewardCategory", b =>
                {
                    b.HasOne("CreditCardRewards.Data.Models.CreditCard", "CreditCard")
                        .WithMany("AcceleratedCategories")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.RewardOffer", b =>
                {
                    b.HasOne("CreditCardRewards.Data.Models.CreditCard", "CreditCard")
                        .WithMany("Offers")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.Transaction", b =>
                {
                    b.HasOne("CreditCardRewards.Data.Models.CreditCard", "CreditCard")
                        .WithMany("Transactions")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.CreditCard", b =>
                {
                    b.Navigation("AcceleratedCategories");

                    b.Navigation("Milestones");

                    b.Navigation("Offers");

                    b.Navigation("RewardCaps");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CreditCardRewards.Data.Models.UserProfile", b =>
                {
                    b.Navigation("CreditCards");
                });
#pragma warning restore 612, 618
        }
    }
}
